# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b1b2768b6e03b4b9bee110db2d2d5ed588ba33e1457a4946f78b596a30816f73930b5ee5364828b585f62397036e4360f0da2f7ae90c75cffc046b8fd2b9c25

test:
  secret_key_base: fc73a88b18ba1cdce0aaa48afa44f0a0f7e5a1bfacac6a34413d824a5c90ed3011911a6296cc56e9971e134ad25af82782b67821f5aefa8d218d26d75948d1e8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
